routes/web.php
<?php

use App\Data;
use App\Bonus;
use App\Upgrade;
use App\JOrgChart;
use App\MakeGenealogie;
use App\MakeGenealogieTwo;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::resource('inscription', 'InscriptionController');
Route::resource('groupes_leaders', 'GroupeController');
Route::resource('demandes', 'DemandeController');

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/connexion', 'HomeController@logout')->name('logout');
Route::get('/mon-profil', 'ProfilController@index')->name('myprofil');
Route::get('/profil/{var}', 'ProfilController@create')->name('profil');
Route::post('/profil-update/{var}', 'ProfilController@modif_profil')->name('profil.update');
Route::get('/mdp/{id}', 'ProfilController@modif_pwd')->name('user.pwd');
Route::post('/mdp-update/{id}', 'ProfilController@updatepassword')->name('pwd.update');

//Route::get('/profil/{id}', 'ProfilController@create')->name('profil.edit');
//Route::post('/user-update', 'ProfilController@store')->name('profil.update');
Route::get('recharge', 'RechargeController@create')->name('recharge.create');
Route::post('recharge', 'RechargeController@store')->name('recharge.store');
Route::get('generer', 'RechargeController@affich')->name('generer');
Route::post('generer', 'RechargeController@generer')->name('generer.store');
Route::get('transfert-list', 'TranfertController@index')->name('transfert.index');
Route::get('transfert', 'TranfertController@create')->name('transfert.create');
Route::post('transfert', 'TranfertController@store')->name('transfert.store');
Route::get(' valider_demande', 'TranfertController@valider')->name('valider');

// Route::get('category-tree-view',['uses'=>'CategoryController@manageCategory']);
Route::get('genealogie',['as'=>'genealogie','uses'=>'InscriptionController@manageCategory']);
Route::post('add-parrain',['as'=>'add.parrain','uses'=>'InscriptionController@addParrain']);
// Route::post('add-category',['as'=>'add.category','uses'=>'CategoryController@addCategory']);

Route::get('/proof', function () {
	$data = Data::all ();
    return view('proofs/tables')->withData ( $data );
});

Route::get('/upgrade/{id}', function ($id) {

    if($id != Auth::user()->id){
        $id = Auth::user()->id;
       return redirect()->route('upgrade', $id);
    }

    $upgrade = Upgrade::where('code', '=', $id)->get();
	return view('proofs/upgrade', compact('upgrade'));
})->name('upgrade');

Route::get('/addMembers', function () {
	return view('proofs/addMembers');
});

Route::post('memberscreate','MembersController@create');

Route::get('gene/{code}', function($code){

    $mkg = new MakeGenealogie($code);
    
    return view('proofs.gene')->with('tree', $mkg->treeView());

});

Route::get('/genetwo/{id}', function($id){


    if($id != Auth::user()->id){
        $id = Auth::user()->id;
       return redirect()->route('genealogie', $id);
    }

    $mkg = new MakeGenealogieTwo($id);
    
    return view('proofs.genetwo')->with('tree', $mkg->treeView());

})->name('genealogie');

resources/views/partials/footer.blade.php
<footer>
	<div class="pull-right">
	DK 2018<a href="">All Rights reserved</a>
	</div>
	<div class="clearfix"></div>
</footer>

resources/views/partials/sidebar.blade.php
<div class="col-md-3 left_col">
  <div class="left_col scroll-view">
    <div class="navbar nav_title" style="border: 0;">
      <a href="{{ url('/') }}" class="site_title"><img src="{{asset('theme/images/DK1.jpg')}} " style="width: 35px; height: 35px;"> <span>DK Business</span></a>
    </div>

    <div class="clearfix"></div>

    <!-- menu profile quick info -->
    <div class="profile clearfix">
      <div class="profile_info">
        <span>Bienvenue,</span>
        <h2>{{ Auth::user()->first_name }}</h2>
      </div>
    </div>
    <!-- /menu profile quick info -->

    <br />

    <!-- sidebar menu -->
    <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
      <div class="menu_section">
        <h3>General</h3>
        <ul class="nav side-menu">
          <li><a href="{{route('home')}} "><i class="fa fa-home"></i> Tableau de bord </a></li>
          <li><a href=""><i class="fa fa-home"></i> New Deposit </a></li>
          <li><a><i class="fa fa-edit"></i> Portefeuille <span class="fa fa-chevron-down"></span></a>
            <ul class="nav child_menu">
              <li><a href="{{route('transfert.create')}}"> Transfert de code</a></li>
              <li><a href="{{route('demandes.create')}}">Demande de Retrait</a></li>
            </ul>
          </li>
          <li><a><i class="fa fa-desktop"></i> Historiques <span class="fa fa-chevron-down"></span></a>
            <ul class="nav child_menu">
              <li><a href="{{route('transfert.index')}}">Transferts</a></li>
              <li><a href="">Mon Solde</a></li>
              <li><a href="">Commission</a></li><!-- 
              <li><a href="">Wihdrawal</a></li> -->
            </ul>
          </li>
          <li><a href="{{ route('genealogie', ['id' => Auth::user()->id])}}"><i class="fa fa-sitemap"></i> Généalogie </a></li>
          <li><a href="{{ route('upgrade', ['id' => Auth::user()->id])}}"><i class="fa fa-chevron-up" ></i> Niveau </a></li> 
          <li><a href="{{ url('proof')  }}"><i class="fa fa-bars" ></i> Liste </a></li> 
          <li><a href="{{route('inscription.create')}} "><i class="fa fa-home"></i> Ajouter un membre</a></li>
          @if(Auth::user()->role == 'administrateur')
          <li><a href="{{route('groupes_leaders.index')}} "><i class="fa fa-home"></i> Groupes Leaders</a></li>
          <li><a href="{{route('demandes.index')}} "><i class="fa fa-home"></i> Liste des Demandes</a></li>
          <li><a href="{{route('generer')}} "><i class="fa fa-home"></i> Générer code</a></li>
          <li><a href="{{route('recharge.create')}} "><i class="fa fa-home"></i> Recharge Compte</a></li>
          @endif
          <!-- <li><a><i class="fa fa-bar-chart-o"></i> Niveaux <span class="fa fa-chevron-down"></span></a>
            <ul class="nav child_menu">
              <li><a href="">Niveau 1</a></li>
              <li><a href="">Niveau 2</a></li>
              <li><a href="">Niveau 3</a></li>
              <li><a href="">Niveau 4</a></li>
              <li><a href="">Niveau 5</a></li>
              <li><a href="">Niveau 6</a></li>
            </ul>
          </li> -->
        </ul>
      </div>
      <!-- <div class="menu_section">
        <h3>Settings</h3>
        <ul class="nav side-menu">
          <li><a><i class="fa fa-windows"></i> Mon Compte <span class="fa fa-chevron-down"></span></a>
            <ul class="nav child_menu">
              <li><a href="">Profil</a></li>
              <li><a href="">Mot de passe transactions</a></li>
              <li><a href="">Plain Page</a></li>
            </ul>
          </li>
        </ul>
      </div> -->

    </div>
    <!-- /sidebar menu -->

    <!-- /menu footer buttons -->
    <div class="sidebar-footer hidden-small">

    </div>
    <!-- /menu footer buttons -->
  </div>
</div>
<!-- top nav -->

<div class="top_nav">
  <div class="nav_menu">
    <nav>
      <div class="nav toggle">
        <a id="menu_toggle"><i class="fa fa-bars"></i></a>
      </div>

      <ul class="nav navbar-nav navbar-right">
        <li class="">
          <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false"> {{ Auth::user()->first_name }}
            <span class=" fa fa-angle-down"></span>
          </a>
          <ul class="dropdown-menu dropdown-usermenu pull-right">
            <li><a href="{{ route('myprofil') }}"> Profil</a></li>
            <li><a href="{{ route('logout') }}"><i class="fa fa-sign-out pull-right"></i> Déconnexion</a></li>
          </ul>
        </li>
      </ul>
    </nav>
  </div>
</div>