routes/web.php
<?php

use App\Data;
use App\Bonus;
use App\Upgrade;
use App\JOrgChart;
use App\MakeGenealogie;
use App\MakeGenealogieTwo;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::resource('inscription', 'InscriptionController');
Route::resource('groupes_leaders', 'GroupeController');
Route::resource('demandes', 'DemandeController');

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/connexion', 'HomeController@logout')->name('logout');
Route::get('/mon-profil', 'ProfilController@index')->name('myprofil');
Route::get('/profil/{var}', 'ProfilController@create')->name('profil');
Route::post('/profil-update/{var}', 'ProfilController@modif_profil')->name('profil.update');
Route::get('/mdp/{id}', 'ProfilController@modif_pwd')->name('user.pwd');
Route::post('/mdp-update/{id}', 'ProfilController@updatepassword')->name('pwd.update');

//Route::get('/profil/{id}', 'ProfilController@create')->name('profil.edit');
//Route::post('/user-update', 'ProfilController@store')->name('profil.update');
Route::get('recharge', 'RechargeController@create')->name('recharge.create');
Route::post('recharge', 'RechargeController@store')->name('recharge.store');
Route::get('generer', 'RechargeController@affich')->name('generer');
Route::post('generer', 'RechargeController@generer')->name('generer.store');
Route::get('transfert-list', 'TranfertController@index')->name('transfert.index');
Route::get('transfert', 'TranfertController@create')->name('transfert.create');
Route::post('transfert', 'TranfertController@store')->name('transfert.store');
Route::get(' valider_demande', 'TranfertController@valider')->name('valider');

// Route::get('category-tree-view',['uses'=>'CategoryController@manageCategory']);
Route::get('genealogie',['as'=>'genealogie','uses'=>'InscriptionController@manageCategory']);
Route::post('add-parrain',['as'=>'add.parrain','uses'=>'InscriptionController@addParrain']);
// Route::post('add-category',['as'=>'add.category','uses'=>'CategoryController@addCategory']);

Route::get('/proof', function () {
	$data = Data::all ();
    return view('proofs/tables')->withData ( $data );
});

Route::get('/upgrade/{id}', function ($id) {

    if($id != Auth::user()->id){
        $id = Auth::user()->id;
       return redirect()->route('upgrade', $id);
    }

    $upgrade = Upgrade::where('code', '=', $id)->get();
	return view('proofs/upgrade', compact('upgrade'));
})->name('upgrade');

Route::get('/addMembers', function () {
	return view('proofs/addMembers');
});

Route::post('memberscreate','MembersController@create');

Route::get('gene/{code}', function($code){

    $mkg = new MakeGenealogie($code);
    
    return view('proofs.gene')->with('tree', $mkg->treeView());

});

Route::get('/genetwo/{id}', function($id){


    if($id != Auth::user()->id){
        $id = Auth::user()->id;
       return redirect()->route('genealogie', $id);
    }

    $mkg = new MakeGenealogieTwo($id);
    
    return view('proofs.genetwo')->with('tree', $mkg->treeView());

})->name('genealogie');

resources/views/backend/arbre_binaire.blade.php
@extends('layouts.template')
@section('contenu')
<link href="/css/treeview.css" rel="stylesheet">
  
  <div class="right_col" role="main">
    <div class="">
      <div class="page-title">
        <div class="title_left">
          <h3>Groupes leaders</h3>
        </div>

        <div class="title_right">
          <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
            <div class="input-group">
              <input type="text" class="form-control" placeholder="Search for...">
              <span class="input-group-btn">
                <button class="btn btn-default" type="button">Go!</button>
              </span>
            </div>
          </div>
        </div>
      </div>

      <div class="clearfix"></div>

      <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
          <div class="x_panel">
            <div class="x_title">
              <h2>Genealogie </h2>
              
              <div class="clearfix"></div>
            </div>
            <div class="x_content">
              <ul id="tree1">
                @foreach($categories as $category)
                  <li>
                      {{ $category->pseudo_fils }}
                      @if(count($category->childs))
                          @include('auth.genealogie',['childs' => $category->childs])
                      @endif
                  </li>
                @endforeach
            </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- /page content -->

  <script src="/js/treeview.js"></script>
@stop

resources/views/backend/dashboard.blade.php
@extends('layouts.template')
@section('contenu')
<div class="right_col" role="main">
  <div class="">
    <div class="row top_tiles">
      <div class="animated flipInY col-lg-4 col-md-4 col-sm-6 col-xs-12">
        <div class="tile-stats" style="background-color: violet;">
          <div class="icon"><i class="fa fa-money"></i></div>
          <div class="count">{{$solde}}</div>
          <h3> FCFA</h3>
          <p>Solde</p>
        </div>
      </div>
      <div class="animated flipInY col-lg-4 col-md-4 col-sm-6 col-xs-12">
        <div class="tile-stats" style="background-color: #006600;">
          <div class="icon"><i class="fa fa-comments-o"></i></div>
          <div class="count">{{$code}}</div>
          <h3>Enregistrements</h3>
          <p>Codes</p>
        </div>
      </div>
      <div class="animated flipInY col-lg-4 col-md-4 col-sm-6 col-xs-12">
        <div class="tile-stats" style="background-color: #660066;">
          <div class="icon"><i class="fa fa-sort-amount-desc"></i></div>
          <div class="count">{{ $lev }}</div>
          <h3>Niveau</h3>
          <p>Niveaux </p>
        </div>
      </div>
    </div>
    <div class="row top_tiles">
      <div class="animated flipInY col-lg-6 col-md-6 col-sm-6 col-xs-12">
        <div class="tile-stats" style="background-color: #0000e6;">
          <div class="icon"><i class="fa fa-caret-square-o-right"></i></div>
          <div class="count">{{ $kids }}</div>
          <h3>Nombre de fileuls</h3>
        </div>
      </div>
      <div class="animated flipInY col-lg-6 col-md-6 col-sm-6 col-xs-12">
        <div class="tile-stats" style="background-color: #e62e00;">
          <div class="icon"><i class="fa fa-comments-o"></i></div>
          <div class="count">{{ $bonus }}</div>
          <h3>Bonus</h3>
        </div>
      </div>
      
    </div>
    <div class="row">
      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
          <div class="x_title">
            <h2>Toutes les transactions </h2>
            <ul class="nav navbar-right panel_toolbox">
              <li><a class="collapse-link"><i class="fa fa-chevron-up"></i></a>
              </li><!-- 
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-wrench"></i></a>
                <ul class="dropdown-menu" role="menu">
                  <li><a href="#">Settings 1</a>
                  </li>
                  <li><a href="#">Settings 2</a>
                  </li>
                </ul>
              </li> 
              <li><a class="close-link"><i class="fa fa-close"></i></a>
              </li>-->
            </ul>
            <div class="clearfix"></div>
          </div>
          <div class="x_content">
            
            <table id="datatable" class="table table-striped table-bordered">
              <thead>
                <tr>
                  <th>Date transaction</th>
                  <th>Envoyeur</th>
                  <th>Receveur</th>
                  <th>Motif</th>
                  <th>Montant</th>
                </tr>
              </thead>


              <tbody>
                @foreach($transactions as $transact)
                <tr>
                  <td>{{$transact->date_transact}}</td>
                  <td>{{$transact->sender}}</td>
                  <td>{{$transact->recever}}</td>
                  <td>{{$transact->motif}}</td>
                  <td>{{$transact->mont_transact}}</td>
                </tr>
                @endforeach
                                
              </tbody>
            </table>
          </div>
        </div>
      </div>    
    </div>
  </div>
</div>
@stop

resources/views/backend/demande_retrait.blade.php
@extends('layouts.template')
@section('contenu')
<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3>Demande de retrait </h3>
      </div>
    </div>    
    <div class="clearfix"></div>

    <div class="row">
      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
          <div class="x_content">
            <div class="col-md-12 col-sm-12 col-xs-12 ">
              <form class="form-horizontal" method="POST" action="{{route('demandes.store')}}">
                {{ csrf_field() }}

                <div class="col-md-12 col-sm-12 col-xs-12">
                  <div class="form-group">
                    <label>Date de la demande</label>
                    @if ($errors->has('date_dmde'))
                        <span class="help-block">
                            <strong>{{ $errors->first('date_dmde') }}</strong>
                        </span>
                    @endif
                  </div>
                </div>
                <div class="col-md-12 col-sm-12 col-xs-12">
                  <div class="form-group">
                    <label>Pays habité</label>
                    <input id="pays" type="text" class="form-control" name="pays" value="" required autofocus>
                    @if ($errors->has('pays'))
                        <span class="help-block">
                            <strong>{{ $errors->first('pays') }}</strong>
                        </span>
                    @endif
                  </div>
                </div>
                <div class="col-md-12 col-sm-12 col-xs-12">
                  <div class="form-group">
                    <label>Votre groupe leader</label>
                    <select class="form-control" name="group_id" required>
                      <option></option>
                      @foreach($groupes as $group)
                      <option value="{{$group->id}}"> {{$group->nom_group}} </option>
                      @endforeach
                    </select>
                  </div>
                </div> 
                <div class="col-md-12 col-sm-12 col-xs-12">
                  <div class="form-group">
                    <label>Montant à retirer</label>
                    <input id="mont_dmde" type="text" onkeypress="return (event.charCode == 8 || event.charCode == 0 || event.charCode == 13) ? null : event.charCode >= 48 && event.charCode <= 57" class="form-control" name="mont_dmde" value="" required autofocus>
                    @if ($errors->has('mont_dmde'))
                        <span class="help-block">
                            <strong>{{ $errors->first('mont_dmde') }}</strong>
                        </span>
                    @endif
                  </div>
                </div>
                
                <div class="ln_solid"></div>
                <div class="form-group">
                  <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                  <button class="btn btn-primary" type="reset">Annuler</button>
                    <button type="submit" class="btn btn-success">Sauvegarder</button>
                  </div>
                </div>
              </form>             

            </div>
           
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
@stop

resources/views/backend/paiement_inscription.blade.php
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <!-- Meta, title, CSS, favicons, etc. -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Gentelella Alela! | </title>

   <!-- Bootstrap -->
    <link href="{{asset('theme/css/bootstrap/bootstrap.min.css')}}" rel="stylesheet">
    <!-- Font Awesome -->
    <link href="{{asset('theme/css/font-awesome/css/font-awesome.min.css')}}" rel="stylesheet">
    <!-- NProgress -->
    <link href="{{asset('theme/css/nprogress/nprogress.css')}}" rel="stylesheet">
    <!-- bootstrap-daterangepicker -->
    <link href="{{asset('theme/css/bootstrap-daterangepicker/daterangepicker.css')}}" rel="stylesheet">

    <!-- Custom Theme Style -->
    <link href="{{asset('theme/build/css/custom.min.css')}}" rel="stylesheet">
  </head>

  <body class="login">
    <div>      
      <div class="col-md-8 center-margin">    
      <h3>Validation inscription</h3>   
      <form class="form-horizontal" method="POST" action="{{ route('register') }}">
                        {{ csrf_field() }}
        
        <h3>Payeur</h3>
        <input type="text" class="hidden"  name="user_id" value="{{ Auth::user()->id }}">
        <div class="col-md-12 col-sm-12 col-xs-12">
          <div class="form-group">
            <label>Nom du payeur</label>
            <input id="nom_payeur" type="text" class="form-control" name="nom_payeur" value="{{ old('nom_payeur') }}" required autofocus>
            @if ($errors->has('nom_payeur'))
                <span class="help-block">
                    <strong>{{ $errors->first('nom_payeur') }}</strong>
                </span>
            @endif
          </div>
        </div>
        <div class="col-md-12 col-sm-12 col-xs-12">
          <div class="form-group">
            <label>Mot de passe transaction </label>
            <input id="mdp_transact" type="mdp_transact" class="form-control" name="mdp_transact" value="{{ old('mdp_transact') }}" required autofocus>
            @if ($errors->has('mdp_transact'))
                <span class="help-block">
                    <strong>{{ $errors->first('mdp_transact') }}</strong>
                </span>
            @endif
          </div>
        </div> 

        <div class="ln_solid"></div>
        <div class="form-group">
          <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
            <button type="submit" class="btn btn-success">Valider</button>
          </div>
        </div>

      </form>
        
      </div>
    </div>
  </body>
</html>

resources/views/backend/transfert.blade.php
@extends('layouts.template')
@section('contenu')
  <div class="right_col" role="main">
    <div class="">
      <div class="page-title">
        <div class="title_left">
          <h3>Transfert de code</h3>
        </div>
      </div>
      <div class="clearfix"></div>
      
      <div class="x_content">
        <br />
          <form class="form-horizontal" method="POST" action="{{ route('transfert.store') }}">
            {{ csrf_field() }}
            
            <div class="col-md-12 col-sm-12 col-xs-12">
              <div class="form-group">
                <label>Pseudo du receveur </label>
                <input id="receveur" type="text" class="form-control" name="receveur" value="{{ old('receveur') }}" required autofocus>
                @if ($errors->has('receveur'))
                    <span class="help-block">
                        <strong>{{ $errors->first('receveur') }}</strong>
                    </span>
                @endif
              </div>
            </div> 
            <div class="col-md-12 col-sm-12 col-xs-12">
              <div class="form-group">
                <label>Motif du transfert </label>
                <input id="motif" type="text" class="form-control" name="motif" value="{{ old('motif') }}" required autofocus>
                @if ($errors->has('motif'))
                    <span class="help-block">
                        <strong>{{ $errors->first('motif') }}</strong>
                    </span>
                @endif
              </div>
            </div> 
            <div class="col-md-12 col-sm-12 col-xs-12">
              <div class="form-group">
                <label>Nombre de codes à transférer </label>
                <input id="mont_transf" type="text" onkeypress="return (event.charCode == 8 || event.charCode == 0 || event.charCode == 13) ? null : event.charCode >= 48 && event.charCode <= 57" class="form-control" name="mont_transf" value="{{ old('mont_transf') }}" required autofocus>
                @if ($errors->has('mont_transf'))
                    <span class="help-block">
                        <strong>{{ $errors->first('mont_transf') }}</strong>
                    </span>
                @endif
              </div>
            </div>
            <div class="col-md-12 col-sm-12 col-xs-12">
              <div class="form-group">
                <label>Mot de passe transaction </label>
                <input id="mdp_transact" type="password" class="form-control" name="mdp_transact" value="{{ old('mdp_transact') }}" required autofocus>
                @if ($errors->has('mdp_transact'))
                    <span class="help-block">
                        <strong>{{ $errors->first('mdp_transact') }}</strong>
                    </span>
                @endif
              </div>
            </div>
            <div class="ln_solid"></div>
            <div class="form-group">
              <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
              <button class="btn btn-primary" type="reset">Annuler</button>
                <button type="submit" class="btn btn-success">Sauvegarder</button>
              </div>
            </div>   
          </form> 
      </div>
    </div>
  </div>
@stop

resources/views/backend/transfert_list.blade.php
@extends('layouts.template')
@section('contenu')
  
   <div class="right_col" role="main">
          <div class="">
            <div class="page-title">
              <div class="title_left">
                <h3>Transferts</h3>
              </div>

              <div class="title_right">
                <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                  <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search for...">
                    <span class="input-group-btn">
                      <button class="btn btn-default" type="button">Go!</button>
                    </span>
                  </div>
                </div>
              </div>
            </div>

            <div class="clearfix"></div>

            <div class="row">
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2>Liste des transferts effectués </h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <a href="{{route('transfert.create')}}">
                        <button type="button" class="btn btn-primary">Nouveau</button>
                      </a>
                      
                    </ul>
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">
                    <table id="datatable" class="table table-striped table-bordered">
                      <thead>
                        <tr>
                          <th>N°</th>
                          <th>Date transfert </th>
                          <th>Receveur</th>
                          <th>Motif</th>
                        </tr>
                      </thead>
                      <tbody>
                        @foreach($tous as $transf)
                        <tr>
                          <td>{{$i++}}</td>
                          <td>{{$transf->created_at}}</td>
                          <td>{{$transf->receveur}}</td>
                          <td>{{$transf->motif}}</td>
                        </tr>
                        @endforeach
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- /page content -->
@stop