routes/web.php
<?php

use App\Data;
use App\Bonus;
use App\Upgrade;
use App\JOrgChart;
use App\MakeGenealogie;
use App\MakeGenealogieTwo;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('/', function () {
    return view('welcome');
});

Auth::routes();
Route::resource('inscription', 'InscriptionController');
Route::resource('groupes_leaders', 'GroupeController');
Route::resource('demandes', 'DemandeController');

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/connexion', 'HomeController@logout')->name('logout');
Route::get('/mon-profil', 'ProfilController@index')->name('myprofil');
Route::get('/profil/{var}', 'ProfilController@create')->name('profil');
Route::post('/profil-update/{var}', 'ProfilController@modif_profil')->name('profil.update');
Route::get('/mdp/{id}', 'ProfilController@modif_pwd')->name('user.pwd');
Route::post('/mdp-update/{id}', 'ProfilController@updatepassword')->name('pwd.update');

//Route::get('/profil/{id}', 'ProfilController@create')->name('profil.edit');
//Route::post('/user-update', 'ProfilController@store')->name('profil.update');
Route::get('recharge', 'RechargeController@create')->name('recharge.create');
Route::post('recharge', 'RechargeController@store')->name('recharge.store');
Route::get('generer', 'RechargeController@affich')->name('generer');
Route::post('generer', 'RechargeController@generer')->name('generer.store');
Route::get('transfert-list', 'TranfertController@index')->name('transfert.index');
Route::get('transfert', 'TranfertController@create')->name('transfert.create');
Route::post('transfert', 'TranfertController@store')->name('transfert.store');
Route::get(' valider_demande', 'TranfertController@valider')->name('valider');

// Route::get('category-tree-view',['uses'=>'CategoryController@manageCategory']);
Route::get('genealogie',['as'=>'genealogie','uses'=>'InscriptionController@manageCategory']);
Route::post('add-parrain',['as'=>'add.parrain','uses'=>'InscriptionController@addParrain']);
// Route::post('add-category',['as'=>'add.category','uses'=>'CategoryController@addCategory']);

Route::get('/proof', function () {
	$data = Data::all ();
    return view('proofs/tables')->withData ( $data );
});

Route::get('/upgrade/{id}', function ($id) {

    if($id != Auth::user()->id){
        $id = Auth::user()->id;
       return redirect()->route('upgrade', $id);
    }

    $upgrade = Upgrade::where('code', '=', $id)->get();
	return view('proofs/upgrade', compact('upgrade'));
})->name('upgrade');

Route::get('/addMembers', function () {
	return view('proofs/addMembers');
});

Route::post('memberscreate','MembersController@create');

Route::get('gene/{code}', function($code){

    $mkg = new MakeGenealogie($code);
    
    return view('proofs.gene')->with('tree', $mkg->treeView());

});

Route::get('/genetwo/{id}', function($id){


    if($id != Auth::user()->id){
        $id = Auth::user()->id;
       return redirect()->route('genealogie', $id);
    }

    $mkg = new MakeGenealogieTwo($id);
    
    return view('proofs.genetwo')->with('tree', $mkg->treeView());

})->name('genealogie');

resources/views/backend/admin/generer.blade.php
@extends('layouts.template')
@section('contenu')
<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3>Générer Code</h3>
      </div>
    </div>    
    <div class="clearfix"></div>

    <div class="row">
      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
          <div class="x_content">
            <div class="col-md-12 col-sm-12 col-xs-12">
              <form class="form-horizontal" method="POST" action="{{route('generer.store')}}">
                {{ csrf_field() }}

                <div class="col-md-12 col-sm-12 col-xs-12">
                  <div class="form-group">
                    <label>Nombre de codes </label>
                    <input id="nbr_code" type="number" min="1" class="form-control" name="nbr_code" value="" required autofocus>
                    @if ($errors->has('nbr_code'))
                        <span class="help-block">
                            <strong>{{ $errors->first('nbr_code') }}</strong>
                        </span>
                    @endif
                  </div>
                </div>
                
                <div class="ln_solid"></div>
                <div class="form-group">
                  <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                    <button type="submit" class="btn btn-success">Generer</button>
                  </div>
                </div>
              </form>             

            </div>
           
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
@stop

resources/views/backend/admin/groupe_index.blade.php
@extends('layouts.template')
@section('contenu')
  
   <div class="right_col" role="main">
          <div class="">
            <div class="page-title">
              <div class="title_left">
                <h3>Groupes leaders</h3>
              </div>

              <div class="title_right">
                <div class="col-md-5 col-sm-5 col-xs-12 form-group pull-right top_search">
                  <div class="input-group">
                    <input type="text" class="form-control" placeholder="Search for...">
                    <span class="input-group-btn">
                      <button class="btn btn-default" type="button">Go!</button>
                    </span>
                  </div>
                </div>
              </div>
            </div>

            <div class="clearfix"></div>

            <div class="row">
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2>Liste des groupes leaders </h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <a href="{{route('groupes_leaders.create')}}">
                        <button type="button" class="btn btn-primary">Nouveau</button>
                      </a>
                      
                    </ul>
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">
                    <table id="datatable" class="table table-striped table-bordered">
                      <thead>
                        <tr>
                          <th>N°</th>
                          <th>Nom du groupe </th>
                          <th>Pays du siege</th>
                          <th>Responsable groupe</th>
                          <th>Contact</th>
                        </tr>
                      </thead>
                      <tbody>
                        @foreach($groupes as $group)
                          <tr>
                            <td>{{$i++}}</td>
                            <td>{{$group->nom_group}}</td>
                            <td>{{$group->pays}}</td>
                            <td>{{$group->responsable}}</td>
                            <td>{{$group->contact}}</td>
                          </tr>
                        @endforeach
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- /page content -->
@stop

resources/views/backend/admin/groupes_create.blade.php
@extends('layouts.template')
@section('contenu')
<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3>Enregistrement d'un Groupe Leader</h3>
      </div>
    </div>    
    <div class="clearfix"></div>

    <div class="row">
      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
          <div class="x_content">
            <div class="col-md-12 col-sm-12 col-xs-12 ">
              <form class="form-horizontal" method="POST" action="{{route('groupes_leaders.store')}}">
                {{ csrf_field() }}

                <div class="col-md-12 col-sm-12 col-xs-12">
                  <div class="form-group">
                    <label>Nom du groupe Leader</label>
                    <input id="nom_group" type="text" class="form-control" name="nom_group" value="" required autofocus>
                    @if ($errors->has('nom_group'))
                        <span class="help-block">
                            <strong>{{ $errors->first('nom_group') }}</strong>
                        </span>
                    @endif
                  </div>
                </div>
                <div class="col-md-12 col-sm-12 col-xs-12">
                  <div class="form-group">
                    <label>Pays du siège</label>
                    <input id="pays" type="text" class="form-control" name="pays" value="" required autofocus>
                    @if ($errors->has('pays'))
                        <span class="help-block">
                            <strong>{{ $errors->first('pays') }}</strong>
                        </span>
                    @endif
                  </div>
                </div>
                <div class="col-md-12 col-sm-12 col-xs-12">
                  <div class="form-group">
                    <label>Responsable du groupe</label>
                    <input id="responsable" type="text" class="form-control" name="responsable" value="" required autofocus>
                    @if ($errors->has('responsable'))
                        <span class="help-block">
                            <strong>{{ $errors->first('responsable') }}</strong>
                        </span>
                    @endif
                  </div>
                </div>

                <div class="col-md-12 col-sm-12 col-xs-12">
                  <div class="form-group">
                    <label>Contact</label>
                    <input id="contact" type="text" class="form-control" name="contact" value="" required autofocus>
                    @if ($errors->has('contact'))
                        <span class="help-block">
                            <strong>{{ $errors->first('contact') }}</strong>
                        </span>
                    @endif
                  </div>
                </div>
                
                <div class="ln_solid"></div>
                <div class="form-group">
                  <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                  <button class="btn btn-primary" type="reset">Annuler</button>
                    <button type="submit" class="btn btn-success">Sauvegarder</button>
                  </div>
                </div>
              </form>             

            </div>
           
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
@stop

resources/views/backend/admin/list_demande.blade.php
@extends('layouts.template')
@section('contenu')
  
   <div class="right_col" role="main">
          <div class="">
            <div class="page-title">
              <div class="title_left">
                <h3>Commandes</h3>
              </div>              
            </div>

            <div class="clearfix"></div>

            <div class="row">
              <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="x_panel">
                  <div class="x_title">
                    <h2>Liste des demandes de retrait non validées </h2>
                    <ul class="nav navbar-right panel_toolbox">
                      <a href="{{route('demandes.create')}}">
                        <button type="button" class="btn btn-primary">Nouveau</button>
                      </a>
                      
                    </ul>
                    <div class="clearfix"></div>
                  </div>
                  <div class="x_content">
                    <table id="datatable" class="table table-striped table-bordered">
                      <thead>
                        <tr>
                          <th>N°</th>
                          <th>Date de la demande </th>
                          <th>Nom demandeur</th>
                          <th>Montant demandé</th>
                          <th>Valider</th>                          
                        </tr>
                      </thead>
                      <tbody>
                        @foreach($demandes as $dmde)
                        <tr>
                          <td>{{$i++}}</td>
                          <td>{{$dmde->date_dmde}}</td>
                          <td>{{$dmde->user_id}}</td>
                          <td>{{$dmde->mont_dmde}}</td>
                          <td><a href="{{route('valider', ['id'=>$dmde->id])}}"> <i class="fa fa-check-square-o"></i></a></td>
                        </tr>
                        @endforeach
                      </tbody>
                    </table>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <!-- /page content -->
@stop

resources/views/backend/admin/recharge_code.blade.php
@extends('layouts.template')
@section('contenu')
<div class="right_col" role="main">
  <div class="">
    <div class="page-title">
      <div class="title_left">
        <h3>Recharger un compte</h3>
      </div>
    </div>    
    <div class="clearfix"></div>

    <div class="row">
      <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
          <div class="x_content">
            <div class="col-md-12 col-sm-12 col-xs-12 ">
              <form class="form-horizontal" method="POST" action="{{route('recharge.store')}}">
                {{ csrf_field() }}

                <div class="col-md-12 col-sm-12 col-xs-12">
                  <div class="form-group">
                    <label>Pseudo de l'utilisateur</label>
                    <input id="pseudo" type="text" class="form-control" name="pseudo" value="" required autofocus>
                    @if ($errors->has('pseudo'))
                        <span class="help-block">
                            <strong>{{ $errors->first('pseudo') }}</strong>
                        </span>
                    @endif
                  </div>
                </div>
                <div class="col-md-12 col-sm-12 col-xs-12">
                  <div class="form-group">
                    <label>Nombre de codes à charger</label>
                    <input id="nbr_code" type="text" onkeypress="return (event.charCode == 8 || event.charCode == 0 || event.charCode == 13) ? null : event.charCode >= 48 && event.charCode <= 57"  class="form-control" name="nbr_code" value="" required autofocus>
                    @if ($errors->has('nbr_code'))
                        <span class="help-block">
                            <strong>{{ $errors->first('nbr_code') }}</strong>
                        </span>
                    @endif
                  </div>
                </div>
                
                <div class="ln_solid"></div>
                <div class="form-group">
                  <div class="col-md-6 col-sm-6 col-xs-12 col-md-offset-3">
                  <button class="btn btn-primary" type="reset">Annuler</button>
                    <button type="submit" class="btn btn-success">Recharger</button>
                  </div>
                </div>
              </form>             

            </div>
           
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
@stop